version: '3'
services:
    # web:
        # build: ./src
        # ports:
        #     - 8080:8080
        # volumes:
        #     - ./src:/go/src/app
        # depends_on:
        #     - db
        # tty: true
    db:
        image: mysql
        container_name: tutorial_db_container
        environment:
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - 3306:3306
        tty: true
        # restart: always....起動→起動中→終了を繰り返すので, dial tcp: lookup tutorial_db_container on 127.0.0.11:53: no such hostとなり、コンテナを発見できない
