name: build_cache_check

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check dir
        run: |
          ls -laG
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./src
          push: false
          tags: sample:v0.0.1
          cache-from: type=gha
          cache-to: type=gha,mode=max