name: build_cache_check

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: src/Dockerfile
          push: false
          tags: sample:v0.0.1
          cache-from: type=registry,ref=sample:buildcache
          cache-to: type=registry,ref=sample:buildcache,mode=max