on: [pull_request]
jobs:
    golangci-lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: golangci-lint
              uses: reviewdog/action-golangci-lint@v2